database_url_secret_arn           = "arn:aws:secretsmanager:ap-southeast-2:819926065191:secret:claims-agent/dev/database-url-i6ytZk"
internal_service_token_secret_arn = "arn:aws:secretsmanager:ap-southeast-2:819926065191:secret:claims-agent/dev/internal-service-token-e82sex"
openai_api_key_secret_arn         = "arn:aws:secretsmanager:ap-southeast-2:819926065191:secret:claims-agent/dev/openai-api-key-p5txeN"
llm_provider                      = "openai"
openai_base_url                   = "https://api.deepseek.com"
document_intelligence_model       = "deepseek-v4-pro"
