from enum import StrEnum


class RecommendationDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_MORE_INFO = "REQUEST_MORE_INFO"
    REFER_TO_HUMAN = "REFER_TO_HUMAN"


class FraudRiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class NextWorkflowAction(StrEnum):
    PROCEED_TO_PAYMENT_GUARDRAILS = "PROCEED_TO_PAYMENT_GUARDRAILS"
    CREATE_HUMAN_REVIEW_TASK = "CREATE_HUMAN_REVIEW_TASK"
    REQUEST_MORE_INFO = "REQUEST_MORE_INFO"
    BLOCK_RECOMMENDED = "BLOCK_RECOMMENDED"


class HumanDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    MODIFY_PAYOUT = "MODIFY_PAYOUT"
    REQUEST_MORE_INFO = "REQUEST_MORE_INFO"
    ESCALATE = "ESCALATE"
