from enum import Enum

class ClaimStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    IN_REVIEW = "IN_REVIEW"
    COMPLETED = "COMPLETED"

class ClaimType(str, Enum):
    HEALTH = "HEALTH"
    AUTO = "AUTO"
    HOME = "HOME"   

class WorkflowStep(str, Enum):
    INITIAL_REVIEW = "INITIAL_REVIEW"
    DOCUMENT_VERIFICATION = "DOCUMENT_VERIFICATION"
    CLAIM_ASSESSMENT = "CLAIM_ASSESSMENT"
    FINAL_APPROVAL = "FINAL_APPROVAL"
    COMPLETED = "COMPLETED"
    
class WorkflowError(str, Enum):
    INVALID_DOCUMENT = "INVALID_DOCUMENT"
    MISSING_INFORMATION = "MISSING_INFORMATION"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    
class ClaimPlanStep(str, Enum):
    INITIAL_REVIEW = "INITIAL_REVIEW"
    DOCUMENT_VERIFICATION = "DOCUMENT_VERIFICATION"
    CLAIM_ASSESSMENT = "CLAIM_ASSESSMENT"
    FINAL_APPROVAL = "FINAL_APPROVAL"
    COMPLETED = "COMPLETED" 